[package]
edition = "2021"
name = "gapids"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.0", features = ["derive"]}
oauth2 = "*"
serde = "*"
serde_json = "*"
