name: "Dry-run publishing to crates.io"

on: push

jobs:
  pre-publish:
    name: Publish egads
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Publish egads to crates.io
        uses: katyo/publish-crates@v1
        with:
          dry-run: true
          ignore-unpublished-changes: true
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
